const FOOD_DATABASE = [
  {
    id: 'chicken-breast',
    name: 'Grilled Chicken Breast',
    category: 'Protein',
    serving: '100g',
    protein: 31,
    carbs: 0,
    fat: 3.6,
    sugar: 0,
    satFat: 1,
    micros: { sodium: '74mg', potassium: '256mg', iron: '5%', vitaminB6: '30%' },
    allergens: []
  },
  {
    id: 'salmon-fillet',
    name: 'Baked Salmon Fillet',
    category: 'Protein / Healthy Fat',
    serving: '100g',
    protein: 22,
    carbs: 0,
    fat: 13,
    sugar: 0,
    satFat: 2.5,
    micros: { omega3: '2.3g', vitaminD: '100%', potassium: '363mg', cobalamin: '50%' },
    allergens: ['fish']
  },
  {
    id: 'eggs-large',
    name: 'Whole Boiled Egg',
    category: 'Protein',
    serving: '1 egg (50g)',
    protein: 6.3,
    carbs: 0.4,
    fat: 5.3,
    sugar: 0.2,
    satFat: 1.6,
    micros: { choline: '147mg', vitaminA: '5%', iron: '4%', calcium: '2%' },
    allergens: ['egg']
  },
  {
    id: 'greek-yogurt',
    name: 'Plain Non-Fat Greek Yogurt',
    category: 'Dairy / Protein',
    serving: '170g',
    protein: 17,
    carbs: 6,
    fat: 0.7,
    sugar: 6,
    satFat: 0.2,
    micros: { calcium: '18%', potassium: '240mg', cobalamin: '20%' },
    allergens: ['dairy', 'milk']
  },
  {
    id: 'oats',
    name: 'Rolled Oats (Dry)',
    category: 'Carbohydrates',
    serving: '50g',
    protein: 6.5,
    carbs: 34,
    fat: 3.5,
    sugar: 0.5,
    satFat: 0.6,
    micros: { fiber: '5g', iron: '10%', magnesium: '15%', zinc: '8%' },
    allergens: ['gluten']
  },
  {
    id: 'brown-rice',
    name: 'Cooked Brown Rice',
    category: 'Carbohydrates',
    serving: '150g',
    protein: 4.5,
    carbs: 38,
    fat: 1.4,
    sugar: 0.5,
    satFat: 0.3,
    micros: { fiber: '2.7g', magnesium: '11%', manganese: '44%' },
    allergens: []
  },
  {
    id: 'sweet-potato',
    name: 'Baked Sweet Potato',
    category: 'Carbohydrates',
    serving: '130g',
    protein: 2.6,
    carbs: 27,
    fat: 0.2,
    sugar: 7.4,
    satFat: 0.05,
    micros: { fiber: '4g', vitaminA: '400%', vitaminC: '25%', potassium: '475mg' },
    allergens: []
  },
  {
    id: 'avocado',
    name: 'Fresh Avocado',
    category: 'Healthy Fat',
    serving: '100g',
    protein: 2,
    carbs: 8.5,
    fat: 15,
    sugar: 0.7,
    satFat: 2.1,
    micros: { fiber: '6.7g', potassium: '485mg', vitaminE: '10%', vitaminK: '26%' },
    allergens: []
  },
  {
    id: 'almonds',
    name: 'Raw Almonds',
    category: 'Nuts / Fat',
    serving: '30g',
    protein: 6,
    carbs: 6,
    fat: 15,
    sugar: 1.2,
    satFat: 1.1,
    micros: { fiber: '3.5g', magnesium: '20%', vitaminE: '37%', calcium: '7%' },
    allergens: ['nuts', 'tree nuts', 'almond']
  },
  {
    id: 'apple-red',
    name: 'Fresh Red Apple',
    category: 'Fruits',
    serving: '1 medium (182g)',
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
    sugar: 19,
    satFat: 0.05,
    micros: { fiber: '4.4g', vitaminC: '14%', potassium: '195mg' },
    allergens: []
  },
  {
    id: 'banana',
    name: 'Fresh Ripe Banana',
    category: 'Fruits',
    serving: '1 medium (118g)',
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    sugar: 14,
    satFat: 0.1,
    micros: { fiber: '3.1g', vitaminB6: '33%', vitaminC: '11%', potassium: '422mg' },
    allergens: []
  },
  {
    id: 'broccoli',
    name: 'Steamed Broccoli',
    category: 'Vegetables',
    serving: '150g',
    protein: 3.7,
    carbs: 8,
    fat: 0.6,
    sugar: 2.1,
    satFat: 0.1,
    micros: { fiber: '3.8g', vitaminC: '135%', vitaminK: '115%', folate: '14%' },
    allergens: []
  },
  {
    id: 'peanut-butter',
    name: 'Natural Peanut Butter',
    category: 'Fats / Protein',
    serving: '32g (2 tbsp)',
    protein: 8,
    carbs: 7,
    fat: 16,
    sugar: 2,
    satFat: 3.3,
    micros: { magnesium: '12%', vitaminB3: '25%', vitaminE: '15%' },
    allergens: ['nuts', 'peanuts']
  },
  {
    id: 'whey-protein',
    name: 'Whey Protein Isolate Powder',
    category: 'Supplement / Protein',
    serving: '30g (1 scoop)',
    protein: 25,
    carbs: 1.5,
    fat: 0.5,
    sugar: 0.5,
    satFat: 0.2,
    micros: { calcium: '12%', BCAA: '5.5g', glutamine: '4g' },
    allergens: ['dairy', 'milk', 'whey']
  },
  {
    id: 'dark-chocolate',
    name: 'Dark Chocolate (85% Cacao)',
    category: 'Sweets / Treats',
    serving: '30g',
    protein: 3.6,
    carbs: 13,
    fat: 14,
    sugar: 4,
    satFat: 8.5,
    micros: { fiber: '3.3g', iron: '33%', magnesium: '38%', copper: '50%' },
    allergens: ['dairy']
  }
];

const MEAL_RECIPE_DATABASE = {
  breakfast: [
    {
      name: "High Protein Oatmeal & Fruit Bowl",
      baseCalories: 400,
      protein: 28,
      carbs: 52,
      fat: 9,
      sugar: 12,
      satFat: 1.5,
      ingredients: ["rolled oats", "egg whites or whey protein", "berries", "chia seeds", "cinnamon"],
      allergens: ["gluten", "dairy", "egg"],
      prepTime: "10 mins",
      instructions: "Cook rolled oats in water or milk. Stir in protein source, top with fresh berries and chia seeds."
    },
    {
      name: "Avocado & Egg White Veggie Toast",
      baseCalories: 380,
      protein: 24,
      carbs: 35,
      fat: 14,
      sugar: 4,
      satFat: 2.5,
      ingredients: ["whole grain bread", "egg whites", "fresh avocado", "spinach", "cherry tomatoes"],
      allergens: ["gluten", "egg"],
      prepTime: "12 mins",
      instructions: "Toast whole grain bread, scramble egg whites with spinach, spread mashed avocado and top with tomatoes."
    },
    {
      name: "Greek Yogurt Berry Parfait",
      baseCalories: 320,
      protein: 26,
      carbs: 40,
      fat: 4,
      sugar: 15,
      satFat: 1.0,
      ingredients: ["non-fat greek yogurt", "strawberries", "blueberries", "honey", "pumpkin seeds"],
      allergens: ["dairy", "milk"],
      prepTime: "5 mins",
      instructions: "Layer Greek yogurt with fresh berries and top with a drizzle of honey and pumpkin seeds."
    },
    {
      name: "Plant-Based Banana Oat Smoothie",
      baseCalories: 350,
      protein: 20,
      carbs: 55,
      fat: 6,
      sugar: 18,
      satFat: 0.8,
      ingredients: ["pea protein powder", "banana", "rolled oats", "almond milk", "flaxseed"],
      allergens: ["gluten", "nuts", "almond"],
      prepTime: "5 mins",
      instructions: "Blend pea protein, ripe banana, oats, almond milk, and flaxseed until smooth."
    }
  ],
  lunch: [
    {
      name: "Mediterranean Grilled Chicken & Quinoa Salad",
      baseCalories: 520,
      protein: 42,
      carbs: 48,
      fat: 16,
      sugar: 5,
      satFat: 2.8,
      ingredients: ["grilled chicken breast", "cooked quinoa", "cucumber", "extra virgin olive oil", "lemon juice", "feta cheese"],
      allergens: ["dairy"],
      prepTime: "20 mins",
      instructions: "Toss diced grilled chicken, cooked quinoa, sliced cucumbers, and lemon-olive oil dressing."
    },
    {
      name: "Seared Salmon with Sweet Potato & Asparagus",
      baseCalories: 560,
      protein: 38,
      carbs: 42,
      fat: 22,
      sugar: 8,
      satFat: 4.0,
      ingredients: ["wild salmon fillet", "baked sweet potato", "steamed asparagus", "olive oil"],
      allergens: ["fish"],
      prepTime: "25 mins",
      instructions: "Pan-sear salmon in olive oil, serve alongside baked sweet potato wedges and steamed asparagus."
    },
    {
      name: "Lean Beef & Brown Rice Power Bowl",
      baseCalories: 580,
      protein: 45,
      carbs: 54,
      fat: 18,
      sugar: 3,
      satFat: 5.2,
      ingredients: ["extra lean ground beef", "cooked brown rice", "steamed broccoli", "sesame seeds", "low-sodium soy sauce"],
      allergens: ["soy", "sesame"],
      prepTime: "20 mins",
      instructions: "Sauté lean beef with garlic and soy sauce, serve over brown rice and steamed broccoli."
    },
    {
      name: "Lentil & Chickpea Veggie Harvest Bowl",
      baseCalories: 480,
      protein: 26,
      carbs: 68,
      fat: 10,
      sugar: 6,
      satFat: 1.2,
      ingredients: ["brown lentils", "chickpeas", "roasted zucchini", "bell peppers", "tahini dressing"],
      allergens: ["sesame"],
      prepTime: "20 mins",
      instructions: "Combine warm lentils, roasted vegetables, chickpeas, and drizzle with light tahini."
    }
  ],
  dinner: [
    {
      name: "Herb Baked Turkey Breast with Roasted Vegetables",
      baseCalories: 460,
      protein: 44,
      carbs: 32,
      fat: 12,
      sugar: 6,
      satFat: 2.0,
      ingredients: ["turkey breast", "roasted cauliflower", "carrots", "olive oil", "rosemary"],
      allergens: [],
      prepTime: "30 mins",
      instructions: "Season turkey breast with herbs and olive oil, roast with carrots and cauliflower."
    },
    {
      name: "Pan-Seared White Fish with Quinoa & Steamed Broccoli",
      baseCalories: 420,
      protein: 38,
      carbs: 44,
      fat: 9,
      sugar: 3,
      satFat: 1.5,
      ingredients: ["cod fillet", "quinoa", "steamed broccoli", "lemon", "parsley"],
      allergens: ["fish"],
      prepTime: "20 mins",
      instructions: "Pan-fry cod with lemon juice and herbs. Serve over fluffy cooked quinoa and broccoli."
    },
    {
      name: "Tofu & Mixed Veggie Stir-Fry",
      baseCalories: 400,
      protein: 24,
      carbs: 46,
      fat: 14,
      sugar: 7,
      satFat: 2.1,
      ingredients: ["firm tofu", "jasmine rice", "bell peppers", "snap peas", "tamari soy sauce"],
      allergens: ["soy"],
      prepTime: "15 mins",
      instructions: "Cube tofu and crisp in pan, stir-fry veggies with soy sauce, and serve over jasmine rice."
    },
    {
      name: "Lean Steak & Baked Potato Supreme",
      baseCalories: 550,
      protein: 46,
      carbs: 45,
      fat: 18,
      sugar: 4,
      satFat: 6.0,
      ingredients: ["sirloin steak", "russet potato", "green beans", "olive oil"],
      allergens: [],
      prepTime: "25 mins",
      instructions: "Grill sirloin steak to medium. Pair with a fluffy baked potato and garlic green beans."
    }
  ],
  sweet: [
    {
      name: "Protein Chocolate Chia Pudding",
      baseCalories: 220,
      protein: 14,
      carbs: 22,
      fat: 8,
      sugar: 5,
      satFat: 1.2,
      ingredients: ["chia seeds", "unsweetened almond milk", "cocoa powder", "whey protein", "stevia"],
      allergens: ["dairy", "milk", "nuts", "almond"],
      prepTime: "5 mins (Chill 2 hrs)",
      instructions: "Whisk chia seeds, cocoa powder, protein powder, and almond milk. Chill until set."
    },
    {
      name: "Fresh Berry & Greek Yogurt Whip",
      baseCalories: 180,
      protein: 16,
      carbs: 20,
      fat: 2,
      sugar: 12,
      satFat: 0.5,
      ingredients: ["greek yogurt", "raspberries", "blueberries", "vanilla extract"],
      allergens: ["dairy", "milk"],
      prepTime: "5 mins",
      instructions: "Whip Greek yogurt with vanilla extract. Top with fresh vibrant berries."
    },
    {
      name: "Baked Cinnamon Apple with Almond Crunch",
      baseCalories: 190,
      protein: 4,
      carbs: 32,
      fat: 6,
      sugar: 18,
      satFat: 0.5,
      ingredients: ["apple", "cinnamon", "crushed almonds", "drizzle of honey"],
      allergens: ["nuts", "almonds", "tree nuts"],
      prepTime: "15 mins",
      instructions: "Core apple, sprinkle with cinnamon and crushed almonds. Bake until tender."
    },
    {
      name: "Dark Chocolate & Peanut Butter Banana Bites",
      baseCalories: 210,
      protein: 6,
      carbs: 25,
      fat: 10,
      sugar: 13,
      satFat: 3.5,
      ingredients: ["banana", "peanut butter", "dark chocolate (85%)"],
      allergens: ["peanuts", "nuts", "dairy"],
      prepTime: "10 mins",
      instructions: "Slice banana, sandwich with peanut butter, dip in melted dark chocolate, freeze 20 mins."
    }
  ]
};
