class FoodItem {
  final String id;
  final String name;
  final String category;
  final String serving;
  final double protein;
  final double carbs;
  final double fat;
  final double sugar;
  final double satFat;
  final Map<String, String> micros;
  final List<String> allergens;

  const FoodItem({
    required this.id,
    required this.name,
    required this.category,
    required this.serving,
    required this.protein,
    required this.carbs,
    required this.fat,
    required this.sugar,
    required this.satFat,
    required this.micros,
    required this.allergens,
  });
}

const List<FoodItem> foodDatabase = [
  FoodItem(
    id: 'chicken-breast',
    name: 'Grilled Chicken Breast',
    category: 'Protein',
    serving: '100g',
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    sugar: 0.0,
    satFat: 1.0,
    micros: {'Sodium': '74mg', 'Potassium': '256mg', 'Iron': '5%', 'Vitamin B6': '30%'},
    allergens: [],
  ),
  FoodItem(
    id: 'salmon-fillet',
    name: 'Baked Salmon Fillet',
    category: 'Protein / Healthy Fat',
    serving: '100g',
    protein: 22.0,
    carbs: 0.0,
    fat: 13.0,
    sugar: 0.0,
    satFat: 2.5,
    micros: {'Omega-3': '2.3g', 'Vitamin D': '100%', 'Potassium': '363mg', 'Cobalamin': '50%'},
    allergens: ['fish'],
  ),
  FoodItem(
    id: 'eggs-large',
    name: 'Whole Boiled Egg',
    category: 'Protein',
    serving: '1 egg (50g)',
    protein: 6.3,
    carbs: 0.4,
    fat: 5.3,
    sugar: 0.2,
    satFat: 1.6,
    micros: {'Choline': '147mg', 'Vitamin A': '5%', 'Iron': '4%', 'Calcium': '2%'},
    allergens: ['egg'],
  ),
  FoodItem(
    id: 'greek-yogurt',
    name: 'Plain Non-Fat Greek Yogurt',
    category: 'Dairy / Protein',
    serving: '170g',
    protein: 17.0,
    carbs: 6.0,
    fat: 0.7,
    sugar: 6.0,
    satFat: 0.2,
    micros: {'Calcium': '18%', 'Potassium': '240mg', 'Vitamin B12': '20%'},
    allergens: ['dairy', 'milk'],
  ),
  FoodItem(
    id: 'oats',
    name: 'Rolled Oats (Dry)',
    category: 'Carbohydrates',
    serving: '50g',
    protein: 6.5,
    carbs: 34.0,
    fat: 3.5,
    sugar: 0.5,
    satFat: 0.6,
    micros: {'Fiber': '5g', 'Iron': '10%', 'Magnesium': '15%', 'Zinc': '8%'},
    allergens: ['gluten'],
  ),
  FoodItem(
    id: 'brown-rice',
    name: 'Cooked Brown Rice',
    category: 'Carbohydrates',
    serving: '150g',
    protein: 4.5,
    carbs: 38.0,
    fat: 1.4,
    sugar: 0.5,
    satFat: 0.3,
    micros: {'Fiber': '2.7g', 'Magnesium': '11%', 'Manganese': '44%'},
    allergens: [],
  ),
  FoodItem(
    id: 'sweet-potato',
    name: 'Baked Sweet Potato',
    category: 'Carbohydrates',
    serving: '130g',
    protein: 2.6,
    carbs: 27.0,
    fat: 0.2,
    sugar: 7.4,
    satFat: 0.05,
    micros: {'Fiber': '4g', 'Vitamin A': '400%', 'Vitamin C': '25%', 'Potassium': '475mg'},
    allergens: [],
  ),
  FoodItem(
    id: 'avocado',
    name: 'Fresh Avocado',
    category: 'Healthy Fat',
    serving: '100g',
    protein: 2.0,
    carbs: 8.5,
    fat: 15.0,
    sugar: 0.7,
    satFat: 2.1,
    micros: {'Fiber': '6.7g', 'Potassium': '485mg', 'Vitamin E': '10%', 'Vitamin K': '26%'},
    allergens: [],
  ),
  FoodItem(
    id: 'almonds',
    name: 'Raw Almonds',
    category: 'Nuts / Fat',
    serving: '30g',
    protein: 6.0,
    carbs: 6.0,
    fat: 15.0,
    sugar: 1.2,
    satFat: 1.1,
    micros: {'Fiber': '3.5g', 'Magnesium': '20%', 'Vitamin E': '37%', 'Calcium': '7%'},
    allergens: ['nuts', 'tree nuts', 'almond'],
  ),
  FoodItem(
    id: 'apple-red',
    name: 'Fresh Red Apple',
    category: 'Fruits',
    serving: '1 medium (182g)',
    protein: 0.5,
    carbs: 25.0,
    fat: 0.3,
    sugar: 19.0,
    satFat: 0.05,
    micros: {'Fiber': '4.4g', 'Vitamin C': '14%', 'Potassium': '195mg'},
    allergens: [],
  ),
  FoodItem(
    id: 'banana',
    name: 'Fresh Ripe Banana',
    category: 'Fruits',
    serving: '1 medium (118g)',
    protein: 1.3,
    carbs: 27.0,
    fat: 0.4,
    sugar: 14.0,
    satFat: 0.1,
    micros: {'Fiber': '3.1g', 'Vitamin B6': '33%', 'Vitamin C': '11%', 'Potassium': '422mg'},
    allergens: [],
  ),
  FoodItem(
    id: 'broccoli',
    name: 'Steamed Broccoli',
    category: 'Vegetables',
    serving: '150g',
    protein: 3.7,
    carbs: 8.0,
    fat: 0.6,
    sugar: 2.1,
    satFat: 0.1,
    micros: {'Fiber': '3.8g', 'Vitamin C': '135%', 'Vitamin K': '115%', 'Folate': '14%'},
    allergens: [],
  ),
];
